import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "./StoreProvider";

const avenirMedium = localFont({
  src: "./fonts/AvenirLTStd-Medium.otf",
  variable: "--font-avenir-medium",
  weight: "500", // Medium weight
});
const avenirHeavy = localFont({
  src: "./fonts/AvenirLTStd-Heavy.otf",
  variable: "--font-avenir-heavy",
  weight: "500", // Medium weight
});

export const metadata: Metadata = {
  title: "Boiler Plate Next.js 14",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning={true} lang="en" data-theme="customtheme" data-lt-installed="true" >
      <body
        className={`${avenirMedium.variable} ${avenirHeavy.variable} antialiased`}
      >
        <main>
          <StoreProvider>
            {children}
          </StoreProvider>
        </main>
      </body>
    </html>
  );
}
